# Generated by Django 2.2.4 on 2019-08-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.TextField(default='', max_length=250, unique=True),
        ),
    ]
