# Generated by Django 2.2.4 on 2019-08-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_enterprise_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_begin',
            field=models.DateField(),
        ),
    ]
