# Generated by Django 2.2.4 on 2019-08-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190816_0509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
