# Generated by Django 2.2.4 on 2019-08-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190816_2010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='enterprise',
            table='enterprise',
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
