# Generated by Django 2.2.4 on 2019-08-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='price',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Company'),
        ),
    ]
